server:
  host: localhost
  port: 8080
  mode: development

jira:
  url: https://test.atlassian.net
  timeout: 30
  retries: 3
  auth:
    type: api_token
    email: test@example.com

features:
  natural_language: true
  caching: true
  auto_retry: true

logging:
  level: debug
  format: console
  output: stdout

security:
  rate_limit: 100
  enable_cors: true
  allowed_origins:
    - "http://localhost:*"
    - "https://localhost:*"